---
title: "209 Final Project Exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, autodep=TRUE, 
                      cache.comments=FALSE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(synthdid)
```

# Synth-DID

```{r}
raleigh = readRDS('raleigh.rds')
charlotte = readRDS('charlotte.rds')
fayette = readRDS('fayetteville.rds')
win_sal = readRDS('winston_salem.rds')
durham = read.csv('durham.csv')
green = readRDS('greensboro.rds')
```

```{r}
raleigh_g = raleigh %>%
  mutate(m_y = format(date, '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2002-01') &
         (m_y <= '2014-12')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n()) %>% # population as of 2021
  mutate(county = "Raleigh")
```

```{r}
charlotte_g = charlotte %>%
  mutate(m_y = format(date, '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2002-01') &
         (m_y <= '2014-12')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n()) %>% # population as of 2021
  mutate(county = "Charlotte")
```

```{r}
fayette_g = fayette %>%
  mutate(m_y = format(date, '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2002-01') &
         (m_y <= '2014-12')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n()) %>% # population as of 2021
  mutate(county = "Fayetteville")
```

```{r}
win_sal_g = win_sal %>%
  mutate(m_y = format(date, '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2002-01') &
         (m_y <= '2014-12')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n()) %>% # population as of 2021
  mutate(county = "Winston-Salem")
```

```{r}
durham_g = durham %>%
  mutate(m_y = format(as.Date(date), '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2002-01') &
         (m_y <= '2014-12')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n()) %>% # population as of 2021
  mutate(county = "Durham")
```

```{r}
green_g = green %>%
  mutate(m_y = format(date, '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2002-01') &
         (m_y <= '2014-12')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n()) %>% # population as of 2021
  mutate(county = "Greensboro")
```

```{r}
nc = rbind(raleigh_g, charlotte_g, fayette_g, win_sal_g, durham_g, green_g)
nc$m_y = ym(nc$m_y)
```

## White

```{r}
nc_white = nc %>%
  filter(subject_race == 'white')
```

```{r}
nc_white_raleigh = nc_white %>%
  filter(county == "Raleigh")

nc_white_charlotte = nc_white %>%
  filter(county == "Charlotte")

nc_white_win_sal = nc_white %>%
  filter(county == "Winston-Salem")

nc_white_green = nc_white %>%
  filter(county == "Greensboro")
```


```{r}
missing_raleigh = data.frame(m_y = as.Date(c("2004-02-01", "2005-02-01", "2005-05-01", 
                                             "2005-10-01", "2005-11-01", "2006-03-01", 
                                             "2006-08-01", "2007-04-01", "2008-11-01", 
                                             "2009-01-01", "2012-11-01", "2014-07-01",
                                             "2014-10-01")),
                             subject_race = c("white", "white", "white", "white",
                                              "white", "white", "white", "white",
                                              "white", "white", "white", "white",
                                              "white"),
                             total_searches = c(mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2004-01-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2004-03-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-01-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-03-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-04-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-06-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-09-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-09-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2005-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2006-02-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2006-04-01"), ]$total_searches)),
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2006-07-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2006-09-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2007-03-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2007-05-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2008-10-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2008-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2008-12-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2009-02-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2012-10-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2012-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2014-06-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2014-08-01"), ]$total_searches)),
                                                mean(
                               c(nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2014-09-01"), ]$total_searches,
                                 nc_white_raleigh[nc_white_raleigh$m_y == as.Date("2014-11-01"), ]$total_searches))),
                             county = c("Raleigh", "Raleigh", "Raleigh", "Raleigh",
                                        "Raleigh", "Raleigh", "Raleigh", "Raleigh",
                                        "Raleigh", "Raleigh", "Raleigh", "Raleigh",
                                        "Raleigh"))

missing_charlotte = data.frame(m_y = as.Date(c("2008-10-01", "2008-12-01")),
                               subject_race = c("white"),
                               total_searches = c(mean(
                               c(nc_white_charlotte[nc_white_charlotte$m_y == as.Date("2008-09-01"), ]$total_searches,
                                 nc_white_charlotte[nc_white_charlotte$m_y == as.Date("2008-11-01"), ]$total_searches)),
                               mean(
                               c(nc_white_charlotte[nc_white_charlotte$m_y == as.Date("2008-11-01"), ]$total_searches,
                                 nc_white_charlotte[nc_white_charlotte$m_y == as.Date("2009-01-01"), ]$total_searches))),
                               county = c("Charlotte"))

missing_win_sal = data.frame(m_y = as.Date(c("2014-08-01")),
                             subject_race = c("white"),
                             total_searches = c(mean(
                               c(nc_white_win_sal[nc_white_win_sal$m_y == as.Date("2014-07-01"), ]$total_searches,
                                 nc_white_win_sal[nc_white_win_sal$m_y == as.Date("2014-09-01"), ]$total_searches))),
                             county = c("Winston-Salem"))


missing_green = data.frame(m_y = as.Date(c("2005-08-01", "2005-11-01", "2006-11-01",
                                             "2014-03-01")),
                             subject_race = c("white", "white", "white", "white"),
                             total_searches = c(
                               mean(
                               c(nc_white_green[nc_white_green$m_y == as.Date("2005-07-01"), ]$total_searches,
                                 nc_white_green[nc_white_green$m_y == as.Date("2005-09-01"), ]$total_searches)),
                               mean(
                               c(nc_white_green[nc_white_green$m_y == as.Date("2005-10-01"), ]$total_searches,
                                 nc_white_green[nc_white_green$m_y == as.Date("2005-12-01"), ]$total_searches)),
                               mean(
                               c(nc_white_green[nc_white_green$m_y == as.Date("2006-10-01"), ]$total_searches,
                                 nc_white_green[nc_white_green$m_y == as.Date("2006-12-01"), ]$total_searches)),
                               mean(
                               c(nc_white_green[nc_white_green$m_y == as.Date("2014-02-01"), ]$total_searches,
                                 nc_white_green[nc_white_green$m_y == as.Date("2014-04-01"), ]$total_searches))),
                             county = c("Greensboro", "Greensboro", "Greensboro",
                                        "Greensboro"))
```


```{r}
nc_white_a = rbind(nc_white %>%
                     filter(!((m_y == as.Date("2008-10-01"))
                              & (county == "Charlotte")) &
                            !((m_y == as.Date("2005-08-01"))
                              & (county == "Greensboro")) &
                            !((m_y == as.Date("2005-11-01"))
                              & (county == "Greensboro")) &
                            !((m_y == as.Date("2006-11-01"))
                              & (county == "Greensboro")) &
                            !((m_y == as.Date("2014-03-01"))
                              & (county == "Greensboro"))),
                   missing_raleigh,
                   missing_charlotte,
                   missing_win_sal,
                   missing_green)

nc_white_a = nc_white_a %>%
  arrange(county, m_y)
```


```{r}
nc_white_t = nc_white_a %>%
  filter((m_y < as.Date('2013-03-01')) |
         m_y >= as.Date('2014-03-01')) %>%
  mutate(treated = ifelse((m_y >= as.Date('2014-03-01')) & (county == "Greensboro"), 1, 0)) %>%
  select(-c(subject_race)) %>%
  mutate(m_y = format(m_y, '%Y-%m'))
```

```{r}
nc_white_final = data.frame(county = as.factor(nc_white_t$county),
                            year_month = nc_white_t$m_y,
                            total_searches = nc_white_t$total_searches,
                            treated = nc_white_t$treated)
```


```{r}
nc_white_final %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in North Carolina: White Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    # scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

### 2002

```{r}
setup_white = panel.matrices(nc_white_final)
tau.hat = synthdid_estimate(setup_white$Y, setup_white$N0, setup_white$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
sprintf('point estimate: %1.2f', tau.hat)
sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)
plot(tau.hat, se.method='placebo') +
    labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, White Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

```{r}
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.2,
     spaghetti.label.alpha = .2, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, White Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

```{r}
synthdid_units_plot(tau.hat, se.method='placebo')
```

### 2009

```{r}
head(nc_white_final)
```


```{r}
setup_white_09 = panel.matrices(nc_white_final %>%
                               filter(year_month >= "2009-01"))
tau.hat = synthdid_estimate(setup_white_09$Y, setup_white_09$N0, setup_white_09$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.2,
     spaghetti.label.alpha = .2, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, White Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### 2011

```{r}
setup_white_11 = panel.matrices(nc_white_final %>%
                               filter(year_month >= "2011-09"))
tau.hat = synthdid_estimate(setup_white_11$Y, setup_white_11$N0, setup_white_11$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.2,
     spaghetti.label.alpha = .2, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, White Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### No Fayetteville

```{r}
setup_white_11 = panel.matrices(nc_white_final %>%
                               filter(county != "Fayetteville"))
tau.hat = synthdid_estimate(setup_white_11$Y, setup_white_11$N0, setup_white_11$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.2,
     spaghetti.label.alpha = .2, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, White Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

## Black

```{r}
nc_black = nc %>%
  filter(subject_race == 'black')
```

```{r}
nc_black_raleigh = nc_black %>%
  filter(county == "Raleigh")

nc_black_charlotte = nc_black %>%
  filter(county == "Charlotte")

nc_black_win_sal = nc_black %>%
  filter(county == "Winston-Salem")

nc_black_green = nc_black %>%
  filter(county == "Greensboro")
```


```{r}
missing_raleigh_b = data.frame(m_y = as.Date(c("2004-02-01", "2005-02-01", "2005-05-01", 
                                             "2005-10-01", "2005-11-01", "2006-03-01", 
                                             "2006-08-01", "2007-04-01", "2008-11-01", 
                                             "2009-01-01", "2012-11-01", "2014-07-01",
                                             "2014-10-01")),
                             subject_race = c("black", "black", "black", "black",
                                              "black", "black", "black", "black",
                                              "black", "black", "black", "black",
                                              "black"),
                             total_searches = c(mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2004-01-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2004-03-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-01-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-03-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-04-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-06-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-09-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-09-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2005-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2006-02-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2006-04-01"), ]$total_searches)),
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2006-07-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2006-09-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2007-03-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2007-05-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2008-10-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2008-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2008-12-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2009-02-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2012-10-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2012-12-01"), ]$total_searches)), 
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2014-06-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2014-08-01"), ]$total_searches)),
                                                mean(
                               c(nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2014-09-01"), ]$total_searches,
                                 nc_black_raleigh[nc_black_raleigh$m_y == as.Date("2014-11-01"), ]$total_searches))),
                             county = c("Raleigh", "Raleigh", "Raleigh", "Raleigh",
                                        "Raleigh", "Raleigh", "Raleigh", "Raleigh",
                                        "Raleigh", "Raleigh", "Raleigh", "Raleigh",
                                        "Raleigh"))

missing_charlotte_b = data.frame(m_y = as.Date(c("2008-10-01", "2008-12-01")),
                               subject_race = c("white"),
                               total_searches = c(mean(
                               c(nc_black_charlotte[nc_black_charlotte$m_y == as.Date("2008-09-01"), ]$total_searches,
                                 nc_black_charlotte[nc_black_charlotte$m_y == as.Date("2008-11-01"), ]$total_searches)),
                               mean(
                               c(nc_black_charlotte[nc_black_charlotte$m_y == as.Date("2008-11-01"), ]$total_searches,
                                 nc_black_charlotte[nc_black_charlotte$m_y == as.Date("2009-01-01"), ]$total_searches))),
                               county = c("Charlotte")) # not missing, but is quite noisy

missing_win_sal_b = data.frame(m_y = as.Date(c("2014-08-01")),
                             subject_race = c("black"),
                             total_searches = c(mean(
                               c(nc_black_win_sal[nc_black_win_sal$m_y == as.Date("2014-07-01"), ]$total_searches,
                                 nc_black_win_sal[nc_black_win_sal$m_y == as.Date("2014-09-01"), ]$total_searches))),
                             county = c("Winston-Salem"))

missing_green_b = data.frame(m_y = as.Date(c("2005-08-01", "2005-11-01", "2006-11-01",
                                             "2014-03-01")),
                             subject_race = c("black", "black", "black", "black"),
                             total_searches = c(
                               mean(
                               c(nc_black_green[nc_black_green$m_y == as.Date("2005-07-01"), ]$total_searches,
                                 nc_black_green[nc_black_green$m_y == as.Date("2005-09-01"), ]$total_searches)),
                               mean(
                               c(nc_black_green[nc_black_green$m_y == as.Date("2005-10-01"), ]$total_searches,
                                 nc_black_green[nc_black_green$m_y == as.Date("2005-12-01"), ]$total_searches)),
                               mean(
                               c(nc_black_green[nc_black_green$m_y == as.Date("2006-10-01"), ]$total_searches,
                                 nc_black_green[nc_black_green$m_y == as.Date("2006-12-01"), ]$total_searches)),
                               mean(
                               c(nc_black_green[nc_black_green$m_y == as.Date("2014-02-01"), ]$total_searches,
                                 nc_black_green[nc_black_green$m_y == as.Date("2014-04-01"), ]$total_searches))),
                             county = c("Greensboro", "Greensboro", "Greensboro",
                                        "Greensboro"))
```

```{r}
nc_black_final %>%
  filter(county == "Fayetteville") %>%
  filter(year_month <= "2010-01") %>%
  filter(year_month >= "2009-05") %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line()
```


```{r}
nc_black_a = rbind(nc_black %>%
                     filter(!((m_y == as.Date("2008-10-01"))
                              & (county == "Charlotte")) &
                            !((m_y == as.Date("2008-12-01"))
                              & (county == "Charlotte")) &
                            !((m_y == as.Date("2005-08-01"))
                              & (county == "Greensboro")) &
                            !((m_y == as.Date("2005-11-01"))
                              & (county == "Greensboro")) &
                            !((m_y == as.Date("2006-11-01"))
                              & (county == "Greensboro")) &
                            !((m_y == as.Date("2014-03-01"))
                              & (county == "Greensboro"))),
                   missing_raleigh_b,
                   missing_charlotte_b,
                   missing_win_sal_b,
                   missing_green_b)

nc_black_a = nc_black_a %>%
  arrange(county, m_y)
```

```{r}
nc_black_t = nc_black_a %>%
  filter((m_y < as.Date('2013-03-01')) |
         m_y >= as.Date('2014-03-01')) %>%
  mutate(treated = ifelse((m_y >= as.Date('2014-03-01')) & (county == "Greensboro"), 1, 0)) %>%
  select(-c(subject_race)) %>%
  mutate(m_y = format(m_y, '%Y-%m'))
```

```{r}
nc_black_final = data.frame(county = as.factor(nc_black_t$county),
                            year_month = nc_black_t$m_y,
                            total_searches = nc_black_t$total_searches,
                            treated = nc_black_t$treated)
```

### 2002

```{r}
nc_black_final %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in North Carolina: Black Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    # scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

```{r}
setup_black = panel.matrices(nc_black_final)
tau.hat = synthdid_estimate(setup_black$Y, setup_black$N0, setup_black$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, Black Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```


```{r}
synthdid_units_plot(tau.hat, se.method='placebo')
```

### 2009

```{r}
setup_black_09 = panel.matrices(nc_black_final %>%
                               filter(year_month >= "2009-01"))
tau.hat = synthdid_estimate(setup_black_09$Y, setup_black_09$N0, setup_black_09$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, Black Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```


### 2011

```{r}
setup_black_11 = panel.matrices(nc_black_final %>%
                               filter(year_month >= "2011-09"))
tau.hat = synthdid_estimate(setup_black_11$Y, setup_black_11$N0, setup_black_11$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, Black Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### No Durham

```{r}
setup_black = panel.matrices(nc_black_final %>%
                               filter(county != "Durham"))
tau.hat = synthdid_estimate(setup_black$Y, setup_black$N0, setup_black$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, Black Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### No Fayetteville

```{r}
setup_black = panel.matrices(nc_black_final %>%
                               filter(county != "Fayetteville"))
tau.hat = synthdid_estimate(setup_black$Y, setup_black$N0, setup_black$T0)
se = sqrt(vcov(tau.hat, method='placebo'))

te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3, se.method='placebo')  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Total Searches, Black Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```



# Normalized by Population (White only, Black only)

## White

```{r}
nc_white_final_norm = nc_white_final %>%
  mutate(total_searches = ifelse(county=="Greensboro", total_searches/115453*1000,
                                 ifelse(county == "Charlotte", total_searches/347219*1000,
                                        ifelse(county == "Durham", total_searches/115420*1000,
                                               ifelse(county == "Raleigh", total_searches/245575*1000,
                                                      ifelse(county == "Fayetteville", total_searches/72965*1000,
                                                             total_searches/112053*1000))))))

nc_black_final_norm = data.frame(county = nc_white_final_norm$county,
                                 year_month = nc_white_final_norm$year_month,
                                 total_searches = nc_white_final_norm$total_searches,
                                 treated = nc_white_final_norm$treated)
```


### 2002

```{r}
nc_white_final_norm %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Total Searches (Normalized by White Pop. 2020) in NC: White Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    # scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```


```{r}
setup_white_norm = panel.matrices(nc_white_final_norm)
tau.hat = synthdid_estimate(setup_white_norm$Y, setup_white_norm$N0, 
                            setup_white_norm$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method='placebo', spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Normalized Searches, White Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

```{r}
synthdid_units_plot(tau.hat, se.method='placebo')
```

### 2009

```{r}
setup_white_norm = panel.matrices(nc_white_final_norm %>%
                                    filter(year_month >= "2009-01"))
tau.hat = synthdid_estimate(setup_white_norm$Y, setup_white_norm$N0, 
                            setup_white_norm$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method='placebo', spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Normalized Searches, White Subjects (2009)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### 2011

```{r}
setup_white_norm = panel.matrices(nc_white_final_norm %>%
                                    filter(year_month >= "2011-09"))
tau.hat = synthdid_estimate(setup_white_norm$Y, setup_white_norm$N0, 
                            setup_white_norm$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method='placebo', spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Normalized Searches, White Subjects (2011)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```


### No Fayetteville (particularly volatile)

```{r}
setup_white_norm = panel.matrices(nc_white_final_norm %>%
                                    filter(county != "Fayetteville"))
tau.hat = synthdid_estimate(setup_white_norm$Y, setup_white_norm$N0, 
                            setup_white_norm$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method='placebo', spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results; Normalized Searches, White Subjects (No Fayetteville)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```



## Black

```{r}
nc_black_final_norm = nc_black_final %>%
  mutate(total_searches = ifelse(county=="Greensboro", total_searches/128913*1000,
                                 ifelse(county == "Charlotte", total_searches/307862*1000,
                                        ifelse(county == "Durham", total_searches/102375*1000,
                                               ifelse(county == "Raleigh", total_searches/131441*1000,
                                                      ifelse(county == "Fayetteville", total_searches/88391*1000,
                                                             total_searches/82855*1000))))))
```

### 2002

```{r}
nc_black_final_norm %>%
  filter(county != "Durham") %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Total Searches (Normalized by Black Pop. 2020) in NC: Black Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    # scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```


```{r}
setup_black_norm = panel.matrices(nc_black_final_norm)
tau.hat = synthdid_estimate(setup_black_norm$Y, setup_black_norm$N0, 
                            setup_black_norm$T0)
se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method="placebo", spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Normalized Searches, Black Subjects', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

```{r}
synthdid_units_plot(tau.hat, se.method='placebo')
```

### No Durham

```{r}
setup_black_norm = panel.matrices(nc_black_final_norm %>%
                                    filter(county != "Durham"))

tau.hat = synthdid_estimate(setup_black_norm$Y, setup_black_norm$N0, 
                            setup_black_norm$T0)

se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method="placebo", spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results; Normalized Searches, Black Subjects (No Durham)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### No Fayetteville

```{r}
setup_black_norm = panel.matrices(nc_black_final_norm %>%
                                    filter(county != "Fayetteville"))

tau.hat = synthdid_estimate(setup_black_norm$Y, setup_black_norm$N0, 
                            setup_black_norm$T0)

se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method="placebo", spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results; Normalized Searches, Black Subjects (No Fayetteville)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### 2009

```{r}
setup_black_norm = panel.matrices(nc_black_final_norm %>%
                                    filter(year_month >= "2009-01"))

tau.hat = synthdid_estimate(setup_black_norm$Y, setup_black_norm$N0, 
                            setup_black_norm$T0)

se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method="placebo", spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Normalized Searches, Black Subjects (2009)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```

### 2011

```{r}
setup_black_norm = panel.matrices(nc_black_final_norm %>%
                                    filter(year_month >= "2011-09"))

tau.hat = synthdid_estimate(setup_black_norm$Y, setup_black_norm$N0, 
                            setup_black_norm$T0)

se = sqrt(vcov(tau.hat, method='placebo'))
te_est <- sprintf('Point estimate for the treatment effect: %1.2f', tau.hat)
CI <- sprintf('95%% CI (%1.2f, %1.2f)', tau.hat - 1.96 * se, tau.hat + 1.96 * se)

plot(tau.hat, spaghetti.units=rownames(synthdid_controls(tau.hat)),
     se.method="placebo", spaghetti.line.alpha =.3,
     spaghetti.label.alpha = .3)  + 
  labs(x = 'Period', y = 'Searches', title = 'Estimation Results: Normalized Searches, Black Subjects (2011)', 
       subtitle = paste0(te_est, ', ', CI, '.'))
```


# DID with (Total Searches / Population of [subject race] * 100) as Outcome

## White

```{r}
nc_white_final_norm %>%
  filter(year_month >= '2011-09') %>% # 2 periods
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Norm. Searches in Greensboro & Winston-Salem for White Subjects",
         y = "[Searches/[Subject Race] Population]*1000") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

```{r}
nc_white_final_norm %>% 
  filter(year_month >= '2011-09') %>%
  filter((year_month < '2013-03') |
         (year_month >= '2014-03-01')) %>%
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  mutate(time = ifelse(year_month > '2013-03', 1, 0),
         treated = ifelse(county == "Greensboro", 1, 0)) %>%
  lm(total_searches ~ treated*time,
     data = .) %>%
  summary
```

## Black

```{r}
nc_black_final_norm %>%
  filter(year_month >= '2011-09') %>% # two periods
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Norm. Searches in Greensboro & Winston-Salem for Black Subjects",
         y = "[Searches/[Subject Race] Population]*1000")  +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```


```{r}
nc_black_final_norm %>% 
  filter(year_month >= '2011-09') %>%
  filter((year_month < '2013-03') |
         (year_month >= '2014-03-01')) %>%
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  mutate(time = ifelse(year_month > '2013-03', 1, 0),
         treated = ifelse(county == "Greensboro", 1, 0)) %>%
  lm(total_searches ~ treated*time,
     data = .) %>%
  summary
```

# DID w/ Better DF

## White

```{r}
nc_white_final %>%
  filter(year_month >= '2011-09') %>% # two periods
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in Greensboro, NC and Winston-Salem, NC for White Subjects",
         y = "# Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

### 18 mo

```{r}
nc_white_final %>% 
  filter(year_month >= '2011-09') %>%
  filter((year_month < '2013-03') |
         (year_month >= '2014-03-01')) %>%
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  mutate(time = ifelse(year_month > '2013-03', 1, 0),
         treated = ifelse(county == "Greensboro", 1, 0)) %>%
  lm(total_searches ~ treated*time,
     data = .) %>%
  summary
```

### 27 mo

```{r}
nc_white_final %>% 
  filter(year_month >= '2010-12') %>%
  filter((year_month < '2013-03') |
         (year_month >= '2014-03-01')) %>%
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  mutate(time = ifelse(year_month > '2013-03', 1, 0),
         treated = ifelse(county == "Greensboro", 1, 0)) %>%
  lm(total_searches ~ treated*time,
     data = .) %>%
  summary
```


## Black

```{r}
nc_black_final %>%
  filter(year_month >= '2011-09') %>% # two periods
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  ggplot(aes(x = as.Date(ym(year_month)), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in Greensboro, NC and Winston-Salem, NC for Black Subjects",
         y = "# Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-03-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-03-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

### 18 mo

```{r}
nc_black_final %>% 
  filter(year_month >= '2011-09') %>%
  filter((year_month < '2013-03') |
         (year_month >= '2014-03-01')) %>%
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  mutate(time = ifelse(year_month > '2013-03', 1, 0),
         treated = ifelse(county == "Greensboro", 1, 0)) %>%
  lm(total_searches ~ treated*time,
     data = .) %>%
  summary
```

### 27 mo

```{r}
nc_black_final %>% 
  filter(year_month >= '2010-12') %>%
  filter((year_month < '2013-03') |
         (year_month >= '2014-03-01')) %>%
  filter((county == "Greensboro") |
         (county == "Winston-Salem")) %>%
  mutate(time = ifelse(year_month > '2013-03', 1, 0),
         treated = ifelse(county == "Greensboro", 1, 0)) %>%
  lm(total_searches ~ treated*time,
     data = .) %>%
  summary
```


\nepage

# Durham

```{r}
dur_hit = durham %>%
  mutate(m_y = format(as.Date(date), '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2012-01')) %>%
  group_by(m_y) %>%
  summarize(hit_rate = sum(contraband_found)/n())

dur_hit$m_y = ym(dur_hit$m_y)

dur_hit$county = "Durham"

green_dur = rbind(green_hit, dur_hit)
```

```{r}
ggplot(green_dur, 
       aes(x = m_y, y = hit_rate)) +
  geom_line(aes(col=county)) + 
  xlab("") +
  labs(title = "Hit rates in Greensboro, NC and Durham, NC",
       y = "Hit Rate") +
  scale_x_date(date_labels = "%m-%Y") +
  scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_vline(xintercept = as.numeric(as.Date('2013-01-01')), linetype="dashed", 
                color = "black", size=0.75) + 
  geom_vline(xintercept = as.numeric(as.Date('2014-06-01')), linetype="dashed", 
                color = "black", size=0.75) +
  annotate("rect",
           xmin=as.Date('2013-01-01'), 
           xmax=as.Date('2014-06-01'), 
           ymin=-Inf, ymax=Inf,
           alpha = 0.7,
           fill = "gray")
```


## Race

```{r}
dur_hit_r = durham %>%
  mutate(m_y = format(as.Date(date), '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2012-01')) %>%
  group_by(m_y, subject_race) %>%
  summarize(hit_rate = sum(contraband_found)/n())

dur_hit_r$m_y = ym(dur_hit_r$m_y)

dur_hit_r$county = "Durham"

green_dur_r = rbind(green_hit_r, dur_hit_r)
```

```{r}
green_dur_r %>%
  filter(subject_race == "white") %>%
  ggplot(aes(x = as.Date(m_y), y = hit_rate)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Hit rates in Greensboro, NC and Durham, NC for White Subjects",
         y = "Hit Rate") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-01-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-06-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-01-01'), 
             xmax=as.Date('2014-06-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

```{r}
green_dur_r %>%
  filter(subject_race == "black") %>%
  ggplot(aes(x = as.Date(m_y), y = hit_rate)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Hit rates in Greensboro, NC and Durham, NC for Black Subjects",
         y = "Hit Rate") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-01-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-06-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-01-01'), 
             xmax=as.Date('2014-06-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

```{r}
green_dur_r %>%
  filter(subject_race == "hispanic") %>%
  ggplot(aes(x = as.Date(m_y), y = hit_rate)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Hit rates in Greensboro, NC and Durham, NC for Hispanic Subjects",
         y = "Hit Rate") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-01-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-06-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-01-01'), 
             xmax=as.Date('2014-06-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```


## Searches

## Absolute Values

```{r}
dur_tot_r = durham %>%
  mutate(m_y = format(as.Date(date), '%Y-%m')) %>%
  filter((search_conducted == T) &
         (m_y >= '2012-01')) %>%
  group_by(m_y, subject_race) %>%
  summarize(total_searches = n())

dur_tot_r$m_y = ym(dur_tot_r$m_y)
```

```{r}
dur_tot_r$county = "Durham"

green_dur_tot_r = rbind(green_tot_r, dur_tot_r)
green_dur_tot_r = green_dur_tot_r
```

```{r}
green_dur_tot_r %>%
  filter(subject_race == "white") %>%
  ggplot(aes(x = as.Date(m_y), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in Greensboro and Durham for White Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-04-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-04-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

```{r}
green_dur_tot_r %>%
  filter(subject_race == "black") %>%
  ggplot(aes(x = as.Date(m_y), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in Greensboro and Durham for White Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-04-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-04-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```

```{r}
green_dur_tot_r %>%
  filter(subject_race == "hispanic") %>%
  ggplot(aes(x = as.Date(m_y), y = total_searches)) +
    geom_line(aes(col=county)) + 
    xlab("") +
    labs(title = "Searches in Greensboro and Durham for White Subjects",
         y = "Number of Searches") +
    scale_x_date(date_labels = "%m-%Y") +
    scale_color_manual(values=c("#6A7FDB", "#45CB85")) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(xintercept = as.numeric(as.Date('2013-03-01')), linetype="dashed", 
                  color = "black", size=0.75) + 
    geom_vline(xintercept = as.numeric(as.Date('2014-04-01')), linetype="dashed", 
                  color = "black", size=0.75) +
    annotate("rect",
             xmin=as.Date('2013-03-01'), 
             xmax=as.Date('2014-04-01'), 
             ymin=-Inf, ymax=Inf,
             alpha = 0.7,
             fill = "gray")
```



